### ISSUE TITLE
new version 1.3 not available via Ansible-Galaxy

### ISSUE THREAD

**Issue by sseide** [jdauphant/ansible-role-unbound#12]
The new version "1.3" cannot be installed via "ansible-galaxy" Latest version there is "1.2".
This is the version installed with plain "ansible-galaxy install jdauphant.unbound". Explict request version "1.3" with requirements.yml file gives error.

Check with: 
```
curl 'https://galaxy.ansible.com/api/v1/roles/?owner__username=jdauphant&name=unbound' | jq .results[0].summary_fields.versions
```
Output of availabe Versions:
```
[
  {
    "release_date": "2014-08-29T16:17:30Z",
    "id": 2944,
    "name": "v1.0.0"
  },
  {
    "release_date": "2015-01-14T11:38:09Z",
    "id": 2979,
    "name": "v1.0.1"
  },
  {
    "release_date": "2017-06-13T22:05:55Z",
    "id": 33279,
    "name": "v1.0.2"
  },
  {
    "release_date": "2017-10-06T14:25:57Z",
    "id": 39698,
    "name": "v1.0.3"
  },
  {
    "release_date": "2018-04-15T10:32:12Z",
    "id": 56864,
    "name": "v1.2"
  }
]
```

But checking the Galaxy info page at https://galaxy.ansible.com/jdauphant/unbound shows as "Last commit" / "Last import" 19 days ago, therefor version 1.3 should be available... 

Seems to happen from time to time (e.g. https://github.com/ansiblebit/oracle-java/issues/39). May need action from Ansible company itself.

**Comment by jdauphant** [comment]
Thanks @sseide for the report.
I have found the problem, Galaxy wanted a full version, I have created v1.3.0 ;)
